CET322_HW2/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CET322_HW2.Domain;
using CET322_HW2.Models;
using Microsoft.AspNetCore.Mvc;

namespace CET322_HW2.Controllers
{
    public class DepartmentsController : Controller
    {
        SchoolContext _context;

        #region Ctor
        public DepartmentsController(SchoolContext context)
        {
            _context = context;
        }
        #endregion

        #region Methods
        public IList<Student> GetStudentsByDepartmentId(int id)
        {
            IList<Student> students;
            students = _context.Students.Where(x => x.DepartmentId == id).ToList();
            return students;

        }
        #endregion

        public IActionResult Detail(int id)
        {
            var department = _context.Departments.Where(x => x.Id == id).FirstOrDefault();
            if (department != null)
            {
                DepartmentModel departmentModel = new DepartmentModel();
                departmentModel.Name = department.Name;
                departmentModel.Students = GetStudentsByDepartmentId(id);

                return View(departmentModel);

            }
            else
                return NotFound();

        }
        #region List
        public IActionResult DepartmentList()
        {
            var departments = _context.Departments.ToList();
            var departmentsModel = new List<DepartmentModel>();
            foreach (var item in departments)
            {
                var model = new DepartmentModel
                {
                    Id = item.Id,
                    Name = item.Name
                };

                departmentsModel.Add(model);
            }

            return View(departmentsModel);
        }
        #endregion

        #region Create
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DepartmentModel model)
        {
            if (ModelState.IsValid)
            {
                var existingDepartment = _context.Departments.Where(x => x.Name == model.Name).FirstOrDefault();
                if (existingDepartment == null)
                {
                    Department newdepartment = new Department
                    {
                        Name = model.Name
                    };
                    _context.Departments.Add(newdepartment);
                    _context.SaveChanges();
                }
                return RedirectToAction("DepartmentList");
            }
            else
                return View(model);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest();
            }
            var department = _context.Departments.Where(x => x.Id == id).FirstOrDefault();
            if (department == null)
            {
                return NotFound();
            }
            var model = new DepartmentModel
            {
                Id = department.Id,
                Name = department.Name

            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, DepartmentModel model)
        {
            var department = _context.Departments.Where(x => x.Id == model.Id).FirstOrDefault();

            if (!id.HasValue)
            {
                return BadRequest();
            }

            if (department == null)
            {
                return NotFound();
            }

            if (id != department.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid && department != null)
            {
                department.Name = model.Name;
                _context.Departments.Update(department);
                _context.SaveChanges();
                return RedirectToAction("Edit");
            }
            else
            {
                return View(department);

            }


        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var department = _context.Departments.Where(x => x.Id == id).FirstOrDefault();
            if (department != null)
            {
                _context.Departments.Remove(department);
                _context.SaveChanges();

                return RedirectToAction("DepartmentList");
            }
            return NotFound();
        }

        #endregion
    }
}

CET322_HW2/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CET322_HW2.Domain;
using CET322_HW2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CET322_HW2.Controllers
{
    public class StudentsController : Controller
    {
        SchoolContext _context;

        #region Ctor
        public StudentsController(SchoolContext context)
        {
            _context = context;
        }
        #endregion

        #region Methods
        private IList<SelectListItem> GetAvailableDepartments(IList<Department> departments)
        {
            var availableDepartments = new List<SelectListItem>();
            foreach (var department in departments)
            {
                availableDepartments.Add(new SelectListItem
                {
                    Value = department.Id.ToString(),
                    Text = department.Name
                });
               
            }
            availableDepartments.Insert(0,new SelectListItem
            {
                Value = "0",
                Text = "Please select a department"
            });
            return availableDepartments;
        }
        #endregion

        #region List
        public IActionResult StudentList()
        {
            var students = _context.Students.Include(x => x.Department).ToList();
            var studentsmodel = new List<StudentModel>();
            foreach (var item in students)
            {
                var model = new StudentModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    Email = item.Email,
                    SchoolNumber = item.SchoolNumber,
                    Surname = item.Surname,
                    SelectedDepartmentId = item.DepartmentId,
                    Department = item.Department

                };

                studentsmodel.Add(model);
            }

            return View(studentsmodel);
        }
        #endregion

        #region Detail
        public IActionResult Detail(int id)
        {
            var student = _context.Students.Include(x=>x.Department).Where(x => x.Id == id).FirstOrDefault();
            if (student != null)
            {
                StudentModel studentModel = new StudentModel();
                studentModel.Name = student.Name;
                studentModel.Surname = student.Surname;
                studentModel.Email = student.Email;
                studentModel.SchoolNumber = student.SchoolNumber;
                studentModel.SelectedDepartmentId = student.DepartmentId;
                studentModel.Department = student.Department;
                return View(studentModel);

            }
            else
                return NotFound();

        }
        #endregion
        #region Create
        public IActionResult Create()
        {
            StudentModel studentModel = new StudentModel();
            var departments = _context.Departments.OrderBy(x => x.Name).ToList();
            studentModel.AvailableDepartments = GetAvailableDepartments(departments);
            return View(studentModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudentModel model)
        {
            var existingStudent = _context.Students.Where(x => x.SchoolNumber == model.SchoolNumber).FirstOrDefault();
            var department = _context.Departments.Where(x => x.Id == model.SelectedDepartmentId).FirstOrDefault();
            if (ModelState.IsValid && model.SelectedDepartmentId != 0)
            {
                if (existingStudent == null)
                {
                    Student newstudent = new Student
                    {
                        Email = model.Email,
                        Name = model.Name,
                        SchoolNumber = model.SchoolNumber,
                        Surname = model.Surname,
                        DepartmentId = model.SelectedDepartmentId,
                        Department = department

                    };
                    _context.Students.Add(newstudent);
                    _context.SaveChanges();

                }
                return RedirectToAction("StudentList");
            }
            else
            {
                return View(model);
            }
        }
        #endregion

        #region Edit
        public IActionResult Edit(int? id)
        {
            var student = _context.Students.Where(x => x.Id == id).FirstOrDefault();

            if (!id.HasValue)
            {
                return BadRequest();
            }

            if (student == null)
            {
                return NotFound();
            }
            var departments = _context.Departments.OrderBy(x => x.Name).ToList();
            var model = new StudentModel
            {
                Id = student.Id,
                Email = student.Email,
                Name = student.Name,
                SchoolNumber = student.SchoolNumber,
                Surname = student.Surname,
                SelectedDepartmentId = student.DepartmentId,
                AvailableDepartments = GetAvailableDepartments(departments)
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, StudentModel model)
        {
            if (!id.HasValue)
            {
                return BadRequest();
            }

            if (model == null)
            {
                return NotFound();
            }
            var student = _context.Students.Where(x => x.Id == model.Id).FirstOrDefault();
            if (id != student.Id)
                return BadRequest();
            if (ModelState.IsValid && student != null && model.SelectedDepartmentId != 0)
            {
                student.Name = model.Name;
                student.Surname = model.Surname;
                student.SchoolNumber = model.SchoolNumber;
                student.Email = model.Email;
                student.DepartmentId = model.SelectedDepartmentId;
                student.Department = _context.Departments.Where(x => x.Id == model.SelectedDepartmentId).FirstOrDefault();
                _context.Students.Update(student);
                _context.SaveChanges();
                return RedirectToAction("Edit");
            }
            else
            {
                return View(student);

            }


        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var student = _context.Students.Where(x => x.Id == id).FirstOrDefault();
            if (student != null)
            {
                _context.Students.Remove(student);
                _context.SaveChanges();

                return RedirectToAction("StudentList");
            }
            return NotFound();
        }

        #endregion


    }

}

CET322_HW2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" style="width:100px;height:100px;" asp-append-version="true">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="StudentList">All Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="DepartmentList">All Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Merve Ecer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>